/* eslint-disable */
/* tslint:disable */
import {ImageURISource} from "react-native";

/**
 * This file is auto-generated by react-native-image-resource-generator
 * !!! DO NOT EDIT !!!
 * For more information check the documentation:
 * https://github.com/svbutko/react-native-image-resource-generator
*/

export class MockIconsResources {
  static readonly auto: ImageURISource = require("../../resources/images/mockIcons/auto.png");
  static readonly fuel: ImageURISource = require("../../resources/images/mockIcons/fuel.png");
  static readonly geo_mock: ImageURISource = require("../../resources/images/mockIcons/geo_mock.png");
  static readonly market: ImageURISource = require("../../resources/images/mockIcons/market.png");
  static readonly tech: ImageURISource = require("../../resources/images/mockIcons/tech.png");
  static readonly travel: ImageURISource = require("../../resources/images/mockIcons/travel.png");
}

export class TabBarResources {
  static readonly auto: ImageURISource = require("../../resources/images/tabBar/auto.png");
  static readonly main: ImageURISource = require("../../resources/images/tabBar/main.png");
  static readonly market: ImageURISource = require("../../resources/images/tabBar/market.png");
  static readonly services: ImageURISource = require("../../resources/images/tabBar/services.png");
  static readonly travel: ImageURISource = require("../../resources/images/tabBar/travel.png");
}

export class ImageResources {
  static readonly avatar_mock: ImageURISource = require("../../resources/images/avatar_mock.png");
  static readonly tes_logo: ImageURISource = require("../../resources/images/tes_logo.png");
  static readonly widget_warning: ImageURISource = require("../../resources/images/widget_warning.png");
}